site_name: OpenHAIV
nav:
  - Get Started: 
    - Introduction: index.md
    - Quik Start: quik.md
    - Reproduced Methods: methods.md
    - Results: results.md
  - Instructions:
    - Documentation: document.md
  - More Information:
    - People: people.md
theme: readthedocs
